### PR TITLE
Added shortcuts for cfoutput/writeOutput() and abort

### PR DESCRIPTION
**Pull request by mjhagen**
I'm not sure if shortcuts should be in the package, but since they are, I've added some I've used since the ColdFusion Studio days.
I've also removed the `close_lucee_tag` for cfml since that negates the ctrl+/ commenting-shortcut.

_I Have not tested the Mac shortcuts, since I don't have access to one at the moment._

### CODE REVIEW

**Comment by jcberquist** [comment]
I am happy to add the shortcuts. Could you provide more information about the close tags command interfering with the commenting shortcut? That command is a bit buggy, but at least here I don't see the  two key bindings interfering with each other. I do see some situations where the commenting shortcut won't work, given how things are currently scoped, but I can probably improve that.

**Comment by mjhagen** [comment]
ctrl+/ should trigger a line-comment in a script block, but doesn't. When I removed the `close_lucee_tag` block it worked again. I haven't looked into a fix.

**Comment by jcberquist** [comment]
Could you provide an example where the line comment doesn't work for you? At least where I have tried it, it is working correctly, so an example would be very helpful. Also if you open the console in sublime (`CTRL` + backtick) and run `sublime.log_commands(True)` it will start logging all commands to the console (turn off by changing `True` to `False`). With that running, could you try using `CTRL` + `/` where it is not working correctly and seeing which command is run? You could try it with and without the `close_lucee_tag` block to see what difference that makes.

**Comment by mjhagen** [comment]
hmm, I haven't been able to reproduce either so I rolled that part back.

**Comment by jcberquist** [comment]
I want to go ahead and merge this, but do you think you could squash your commits so it comes in as one commit rather than five? See for instance (pulled up by google search): http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by mjhagen** [comment]
Yeah, that's not working... I'm trying all kinds of ways and only making it worse, I'll try again from a clean copy.

**Pull request closed without merging**
